services:
    exercise.gigya_requestor:
        class: Exercise\GigyaBundle\GigyaRequestor
        arguments:
            - %exercise.gigya.api_key%
            - %exercise.gigya.secret_key%
            - @logger

    exercise.gigya_rest.socialize:
        class: Exercise\GigyaBundle\Rest\Socialize
        arguments:
            - @exercise.gigya_requestor

    exercise.gigya_rest.accounts:
        class: Exercise\GigyaBundle\Rest\Accounts
        arguments:
            - @exercise.gigya_requestor
            - %exercise.gigya.login_identifier%

    exercise.gigya_rest.identity_storage:
        class: Exercise\GigyaBundle\Rest\IdentityStorage
        arguments:
            - @exercise.gigya_requestor

    exercise.gigya.event_listener.security:
        class: Exercise\GigyaBundle\EventListener\SecurityListener
        arguments:
            - @exercise.gigya_rest.accounts
            - @exercise.gigya_rest.identity_storage
            - ~
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

