services:
    exercise.gigya:
        class: Exercise\GigyaBundle\Gigya
        arguments:
            - %exercise.gigya.api_key%
            - %exercise.gigya.secret_key%
    exercise.gigya.event_listener.security:
        class: Exercise\GigyaBundle\EventListener\SecurityListener
        arguments: ["@exercise.gigya"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

